[project]
name = "34805-sidar-tannriverdi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.122.0",
    "httpx>=0.28.1",
    "pytest>=9.0.1",
    "ruff>=0.14.6",
    "uvicorn>=0.38.0",
]
